name: Build Wendigo OS

on: [push]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:

  - name: Checkout Repository
    uses: actions/checkout@v3

  - name: Install NASM
    run: sudo apt-get update && sudo apt-get install nasm -y

  - name: Build Bootloader
    run: nasm boot.asm -f bin -o boot.bin

  - name: Build Kernel
    run: nasm kernel.asm -f bin -o kernel.bin

  - name: Create OS Image
    run: cat boot.bin kernel.bin > wendigo.img

  - name: Upload OS Image
    uses: actions/upload-artifact@v3
    with:
      name: wendigo-os
      path: wendigo.img
